# Generated by Django 5.1.6 on 2025-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("balance", models.IntegerField()),
                ("last_reset_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CreditRequest",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_by", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("file_path", models.CharField(max_length=100)),
                ("file_size", models.IntegerField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("content_hash", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentMatch",
            fields=[
                ("match_id", models.AutoField(primary_key=True, serialize=False)),
                ("scan_id", models.IntegerField()),
                ("source_document_id", models.IntegerField()),
                ("matched_document_id", models.IntegerField()),
                ("similarity_score", models.FloatField()),
                ("match_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                ("metadata_id", models.AutoField(primary_key=True, serialize=False)),
                ("document_id", models.IntegerField()),
                ("key", models.CharField(max_length=50)),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.CharField(max_length=100)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanTransaction",
            fields=[
                ("scan_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("document_id", models.IntegerField()),
                ("scan_date", models.DateTimeField()),
                ("credits_used", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("User_id", models.AutoField(primary_key=True, serialize=False)),
                ("Username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("Passwords", models.CharField(max_length=256)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")], max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
